name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: sudo apt-get install composer
      - run: composer install

      - run: touch .env
      - run: echo FACTORIO_API_KEY=${{ secrets.FACTORIO_API_KEY }} >> .env
      - run: echo DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }} >> .env
      - run: echo LOCK_PASSWORD=${{ secrets.LOCK_PASSWORD }} >> .env

      - run: php app.php ci
      - run: php app.php webhook

#      - run: git config user.name "github-actions[bot]"
#      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
#
#      - run: git add -A
#      - run: git commit -m "Increment minor version(s)" || true
#      - run: git push
